/*
 *  Copyright (C) 2020 TechNexion Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


#ifndef __AXONFABRIC_PINS_H
#define __AXONFABRIC_PINS_H


#include <linux/pinctrl/pinctrl.h>


#define AXONF_PIN_DESC(name) PINCTRL_PIN(AXONF_PIN_ ## name, #name)

struct axonf_pingroup {
	const char *name;
	const unsigned pins[1];
	unsigned npins;
};

#define AXONF_PIN_F_GPIO_X1_P66 	0
#define AXONF_PIN_F_GPIO_X1_P68 	1
#define AXONF_PIN_F_GPIO_X1_P70 	2
#define AXONF_PIN_F_GPIO_X1_P72 	3
#define AXONF_PIN_F_GPIO_X1_P74 	4
#define AXONF_PIN_F_GPIO_X1_P76 	5
#define AXONF_PIN_F_GPIO_X1_P78 	6
#define AXONF_PIN_F_GPIO_X1_P80 	7
#define AXONF_PIN_F_GPIO_X2_P18 	8
#define AXONF_PIN_F_GPIO_X2_P20 	9
#define AXONF_PIN_F_GPIO_X2_P22 	10
#define AXONF_PIN_F_GPIO_X2_P24 	11
#define AXONF_PIN_F_GPIO_X3_P65 	12
#define AXONF_PIN_F_GPIO_X3_P67 	13
#define AXONF_PIN_F_GPIO_X3_P69 	14
#define AXONF_PIN_F_GPIO_X3_P71 	15
#define AXONF_PIN_F_GPIO_X4_P7 	16
#define AXONF_PIN_F_GPIO_X4_P8 	17
#define AXONF_PIN_F_GPIO_X4_P19 	18
#define AXONF_PIN_F_GPIO_X4_P20 	19
#define AXONF_PIN_F_GPIO_X4_P32 	20
#define AXONF_PIN_F_GPIO_X4_P34 	21
#define AXONF_PIN_F_GPIO_X4_P40 	22
#define AXONF_PIN_F_DISP_DAT00 	24
#define AXONF_PIN_F_DISP_DAT01 	25
#define AXONF_PIN_F_DISP_DAT02 	26
#define AXONF_PIN_F_DISP_DAT03 	27
#define AXONF_PIN_F_DISP_DAT04 	28
#define AXONF_PIN_F_DISP_DAT05 	29
#define AXONF_PIN_F_DISP_DAT06 	30
#define AXONF_PIN_F_DISP_DAT07 	31
#define AXONF_PIN_F_DISP_DAT08 	32
#define AXONF_PIN_F_DISP_DAT09 	33
#define AXONF_PIN_F_DISP_DAT10 	34
#define AXONF_PIN_F_DISP_DAT11 	35
#define AXONF_PIN_F_DISP_DAT12 	36
#define AXONF_PIN_F_DISP_DAT13 	37
#define AXONF_PIN_F_DISP_DAT14 	38
#define AXONF_PIN_F_DISP_DAT15 	39
#define AXONF_PIN_F_DISP_DAT16 	40
#define AXONF_PIN_F_DISP_DAT17 	41
#define AXONF_PIN_F_DISP_DAT18 	42
#define AXONF_PIN_F_DISP_DAT19 	43
#define AXONF_PIN_F_DISP_DAT20 	44
#define AXONF_PIN_F_DISP_DAT21 	45
#define AXONF_PIN_F_DISP_DAT22 	46
#define AXONF_PIN_F_DISP_DAT23 	47
#define AXONF_PIN_F_DISP_HSYNC 	48
#define AXONF_PIN_F_DISP_VSYNC 	49
#define AXONF_PIN_F_DISP_CLK 	50
#define AXONF_PIN_F_DISP_BKLEN 	51
#define AXONF_PIN_F_DISP_DRDY 	52
#define AXONF_PIN_F_UART_A_TXD 	56
#define AXONF_PIN_F_UART_A_RXD 	57
#define AXONF_PIN_F_UART_A_RTS 	58
#define AXONF_PIN_F_UART_A_CTS 	59
#define AXONF_PIN_F_UART_B_TXD 	60
#define AXONF_PIN_F_UART_B_RXD 	61
#define AXONF_PIN_F_UART_B_RTS 	62
#define AXONF_PIN_F_UART_B_CTS 	63
#define AXONF_PIN_F_UART_C_TXD 	64
#define AXONF_PIN_F_UART_C_RXD 	65
#define AXONF_PIN_F_UART_C_RTS 	66
#define AXONF_PIN_F_UART_C_CTS 	67
#define AXONF_PIN_F_AUD_A_TXD 	68
#define AXONF_PIN_F_AUD_A_TXFS 	69
#define AXONF_PIN_F_AUD_A_TXCLK 	70
#define AXONF_PIN_F_AUD_A_RXD 	71
#define AXONF_PIN_F_SPI_A_MISO 	72
#define AXONF_PIN_F_SPI_A_MOSI 	73
#define AXONF_PIN_F_SPI_A_SCLK 	74
#define AXONF_PIN_F_SPI_A_CS0 	75
#define AXONF_PIN_F_SPI_A_CS1 	76
#define AXONF_PIN_F_PWM_X1_P39 	77
#define AXONF_PIN_F_PWM_X2_P79 	78
#define AXONF_PIN_F_SPI_B_MISO 	80
#define AXONF_PIN_F_SPI_B_MOSI 	81
#define AXONF_PIN_F_SPI_B_SCLK 	82
#define AXONF_PIN_F_SPI_B_CS0 	83
#define AXONF_PIN_F_SPI_B_CS1 	84
#define AXONF_PIN_F_PWM_X4_P1 	85
#define AXONF_PIN_F_PWM_X4_P2 	86
#define AXONF_PIN_F_UART_BT_TXD 	88
#define AXONF_PIN_F_UART_BT_RXD 	89
#define AXONF_PIN_F_UART_BT_RTS 	90
#define AXONF_PIN_F_UART_BT_CTS 	91
#define AXONF_PIN_F_CAN_A_TX 	92
#define AXONF_PIN_F_CAN_A_RX 	93
#define AXONF_PIN_F_CAN_B_TX 	94
#define AXONF_PIN_F_CAN_B_RX 	95
#define AXONF_PIN_F_AUD_B_TXD 	96
#define AXONF_PIN_F_AUD_B_TXFS 	97
#define AXONF_PIN_F_AUD_B_TXCLK 	98
#define AXONF_PIN_F_AUD_B_RXD 	99
#define AXONF_PIN_F_AUD_B_RXFS 	100
#define AXONF_PIN_F_AUD_B_RXCLK 	101
#define AXONF_PIN_F_AUD_B_MCLK 	102

/* PINCTRL DESC */

static const struct pinctrl_pin_desc axonf_pins_desc[] = {
	AXONF_PIN_DESC(F_GPIO_X1_P66),
	AXONF_PIN_DESC(F_GPIO_X1_P68),
	AXONF_PIN_DESC(F_GPIO_X1_P70),
	AXONF_PIN_DESC(F_GPIO_X1_P72),
	AXONF_PIN_DESC(F_GPIO_X1_P74),
	AXONF_PIN_DESC(F_GPIO_X1_P76),
	AXONF_PIN_DESC(F_GPIO_X1_P78),
	AXONF_PIN_DESC(F_GPIO_X1_P80),
	AXONF_PIN_DESC(F_GPIO_X2_P18),
	AXONF_PIN_DESC(F_GPIO_X2_P20),
	AXONF_PIN_DESC(F_GPIO_X2_P22),
	AXONF_PIN_DESC(F_GPIO_X2_P24),
	AXONF_PIN_DESC(F_GPIO_X3_P65),
	AXONF_PIN_DESC(F_GPIO_X3_P67),
	AXONF_PIN_DESC(F_GPIO_X3_P69),
	AXONF_PIN_DESC(F_GPIO_X3_P71),
	AXONF_PIN_DESC(F_GPIO_X4_P7),
	AXONF_PIN_DESC(F_GPIO_X4_P8),
	AXONF_PIN_DESC(F_GPIO_X4_P19),
	AXONF_PIN_DESC(F_GPIO_X4_P20),
	AXONF_PIN_DESC(F_GPIO_X4_P32),
	AXONF_PIN_DESC(F_GPIO_X4_P34),
	AXONF_PIN_DESC(F_GPIO_X4_P40),
	AXONF_PIN_DESC(F_DISP_DAT00),
	AXONF_PIN_DESC(F_DISP_DAT01),
	AXONF_PIN_DESC(F_DISP_DAT02),
	AXONF_PIN_DESC(F_DISP_DAT03),
	AXONF_PIN_DESC(F_DISP_DAT04),
	AXONF_PIN_DESC(F_DISP_DAT05),
	AXONF_PIN_DESC(F_DISP_DAT06),
	AXONF_PIN_DESC(F_DISP_DAT07),
	AXONF_PIN_DESC(F_DISP_DAT08),
	AXONF_PIN_DESC(F_DISP_DAT09),
	AXONF_PIN_DESC(F_DISP_DAT10),
	AXONF_PIN_DESC(F_DISP_DAT11),
	AXONF_PIN_DESC(F_DISP_DAT12),
	AXONF_PIN_DESC(F_DISP_DAT13),
	AXONF_PIN_DESC(F_DISP_DAT14),
	AXONF_PIN_DESC(F_DISP_DAT15),
	AXONF_PIN_DESC(F_DISP_DAT16),
	AXONF_PIN_DESC(F_DISP_DAT17),
	AXONF_PIN_DESC(F_DISP_DAT18),
	AXONF_PIN_DESC(F_DISP_DAT19),
	AXONF_PIN_DESC(F_DISP_DAT20),
	AXONF_PIN_DESC(F_DISP_DAT21),
	AXONF_PIN_DESC(F_DISP_DAT22),
	AXONF_PIN_DESC(F_DISP_DAT23),
	AXONF_PIN_DESC(F_DISP_HSYNC),
	AXONF_PIN_DESC(F_DISP_VSYNC),
	AXONF_PIN_DESC(F_DISP_CLK),
	AXONF_PIN_DESC(F_DISP_BKLEN),
	AXONF_PIN_DESC(F_DISP_DRDY),
	AXONF_PIN_DESC(F_UART_A_TXD),
	AXONF_PIN_DESC(F_UART_A_RXD),
	AXONF_PIN_DESC(F_UART_A_RTS),
	AXONF_PIN_DESC(F_UART_A_CTS),
	AXONF_PIN_DESC(F_UART_B_TXD),
	AXONF_PIN_DESC(F_UART_B_RXD),
	AXONF_PIN_DESC(F_UART_B_RTS),
	AXONF_PIN_DESC(F_UART_B_CTS),
	AXONF_PIN_DESC(F_UART_C_TXD),
	AXONF_PIN_DESC(F_UART_C_RXD),
	AXONF_PIN_DESC(F_UART_C_RTS),
	AXONF_PIN_DESC(F_UART_C_CTS),
	AXONF_PIN_DESC(F_AUD_A_TXD),
	AXONF_PIN_DESC(F_AUD_A_TXFS),
	AXONF_PIN_DESC(F_AUD_A_TXCLK),
	AXONF_PIN_DESC(F_AUD_A_RXD),
	AXONF_PIN_DESC(F_SPI_A_MISO),
	AXONF_PIN_DESC(F_SPI_A_MOSI),
	AXONF_PIN_DESC(F_SPI_A_SCLK),
	AXONF_PIN_DESC(F_SPI_A_CS0),
	AXONF_PIN_DESC(F_SPI_A_CS1),
	AXONF_PIN_DESC(F_PWM_X1_P39),
	AXONF_PIN_DESC(F_PWM_X2_P79),
	AXONF_PIN_DESC(F_SPI_B_MISO),
	AXONF_PIN_DESC(F_SPI_B_MOSI),
	AXONF_PIN_DESC(F_SPI_B_SCLK),
	AXONF_PIN_DESC(F_SPI_B_CS0),
	AXONF_PIN_DESC(F_SPI_B_CS1),
	AXONF_PIN_DESC(F_PWM_X4_P1),
	AXONF_PIN_DESC(F_PWM_X4_P2),
	AXONF_PIN_DESC(F_UART_BT_TXD),
	AXONF_PIN_DESC(F_UART_BT_RXD),
	AXONF_PIN_DESC(F_UART_BT_RTS),
	AXONF_PIN_DESC(F_UART_BT_CTS),
	AXONF_PIN_DESC(F_CAN_A_TX),
	AXONF_PIN_DESC(F_CAN_A_RX),
	AXONF_PIN_DESC(F_CAN_B_TX),
	AXONF_PIN_DESC(F_CAN_B_RX),
	AXONF_PIN_DESC(F_AUD_B_TXD),
	AXONF_PIN_DESC(F_AUD_B_TXFS),
	AXONF_PIN_DESC(F_AUD_B_TXCLK),
	AXONF_PIN_DESC(F_AUD_B_RXD),
	AXONF_PIN_DESC(F_AUD_B_RXFS),
	AXONF_PIN_DESC(F_AUD_B_RXCLK),
	AXONF_PIN_DESC(F_AUD_B_MCLK),
};


/* GPIO groups */

static const char * const gpio_groups[] = {
	"F_GPIO_X1_P66",
	"F_GPIO_X1_P68",
	"F_GPIO_X1_P70",
	"F_GPIO_X1_P72",
	"F_GPIO_X1_P74",
	"F_GPIO_X1_P76",
	"F_GPIO_X1_P78",
	"F_GPIO_X1_P80",
	"F_GPIO_X2_P18",
	"F_GPIO_X2_P20",
	"F_GPIO_X2_P22",
	"F_GPIO_X2_P24",
	"F_GPIO_X3_P65",
	"F_GPIO_X3_P67",
	"F_GPIO_X3_P69",
	"F_GPIO_X3_P71",
	"F_GPIO_X4_P7",
	"F_GPIO_X4_P8",
	"F_GPIO_X4_P19",
	"F_GPIO_X4_P20",
	"F_GPIO_X4_P32",
	"F_GPIO_X4_P34",
	"F_GPIO_X4_P40",
	"F_DISP_DAT00",
	"F_DISP_DAT01",
	"F_DISP_DAT02",
	"F_DISP_DAT03",
	"F_DISP_DAT04",
	"F_DISP_DAT05",
	"F_DISP_DAT06",
	"F_DISP_DAT07",
	"F_DISP_DAT08",
	"F_DISP_DAT09",
	"F_DISP_DAT10",
	"F_DISP_DAT11",
	"F_DISP_DAT12",
	"F_DISP_DAT13",
	"F_DISP_DAT14",
	"F_DISP_DAT15",
	"F_DISP_DAT16",
	"F_DISP_DAT17",
	"F_DISP_DAT18",
	"F_DISP_DAT19",
	"F_DISP_DAT20",
	"F_DISP_DAT21",
	"F_DISP_DAT22",
	"F_DISP_DAT23",
	"F_DISP_HSYNC",
	"F_DISP_VSYNC",
	"F_DISP_CLK",
	"F_DISP_BKLEN",
	"F_DISP_DRDY",
	"F_UART_A_TXD",
	"F_UART_A_RXD",
	"F_UART_A_RTS",
	"F_UART_A_CTS",
	"F_UART_B_TXD",
	"F_UART_B_RXD",
	"F_UART_B_RTS",
	"F_UART_B_CTS",
	"F_UART_C_TXD",
	"F_UART_C_RXD",
	"F_UART_C_RTS",
	"F_UART_C_CTS",
	"F_AUD_A_TXD",
	"F_AUD_A_TXFS",
	"F_AUD_A_TXCLK",
	"F_AUD_A_RXD",
	"F_SPI_A_MISO",
	"F_SPI_A_MOSI",
	"F_SPI_A_SCLK",
	"F_SPI_A_CS0",
	"F_SPI_A_CS1",
	"F_PWM_X1_P39",
	"F_PWM_X2_P79",
	"F_SPI_B_MISO",
	"F_SPI_B_MOSI",
	"F_SPI_B_SCLK",
	"F_SPI_B_CS0",
	"F_SPI_B_CS1",
	"F_PWM_X4_P1",
	"F_PWM_X4_P2",
	"F_UART_BT_TXD",
	"F_UART_BT_RXD",
	"F_UART_BT_RTS",
	"F_UART_BT_CTS",
	"F_CAN_A_TX",
	"F_CAN_A_RX",
	"F_CAN_B_TX",
	"F_CAN_B_RX",
	"F_AUD_B_TXD",
	"F_AUD_B_TXFS",
	"F_AUD_B_TXCLK",
	"F_AUD_B_RXD",
	"F_AUD_B_RXFS",
	"F_AUD_B_RXCLK",
	"F_AUD_B_MCLK",
};


/* Pin groups */

#define AXONF_PINGROUP(pg_name, pin_id) {.name = #pg_name,	.pins = {AXONF_PIN_##pin_id}, .npins = 1,}

static const struct axonf_pingroup axonf_pingroups[] = {
	AXONF_PINGROUP(F_GPIO_X1_P66, F_GPIO_X1_P66),
	AXONF_PINGROUP(F_GPIO_X1_P68, F_GPIO_X1_P68),
	AXONF_PINGROUP(F_GPIO_X1_P70, F_GPIO_X1_P70),
	AXONF_PINGROUP(F_GPIO_X1_P72, F_GPIO_X1_P72),
	AXONF_PINGROUP(F_GPIO_X1_P74, F_GPIO_X1_P74),
	AXONF_PINGROUP(F_GPIO_X1_P76, F_GPIO_X1_P76),
	AXONF_PINGROUP(F_GPIO_X1_P78, F_GPIO_X1_P78),
	AXONF_PINGROUP(F_GPIO_X1_P80, F_GPIO_X1_P80),
	AXONF_PINGROUP(F_GPIO_X2_P18, F_GPIO_X2_P18),
	AXONF_PINGROUP(F_GPIO_X2_P20, F_GPIO_X2_P20),
	AXONF_PINGROUP(F_GPIO_X2_P22, F_GPIO_X2_P22),
	AXONF_PINGROUP(F_GPIO_X2_P24, F_GPIO_X2_P24),
	AXONF_PINGROUP(F_GPIO_X3_P65, F_GPIO_X3_P65),
	AXONF_PINGROUP(F_GPIO_X3_P67, F_GPIO_X3_P67),
	AXONF_PINGROUP(F_GPIO_X3_P69, F_GPIO_X3_P69),
	AXONF_PINGROUP(F_GPIO_X3_P71, F_GPIO_X3_P71),
	AXONF_PINGROUP(F_GPIO_X4_P7, F_GPIO_X4_P7),
	AXONF_PINGROUP(F_GPIO_X4_P8, F_GPIO_X4_P8),
	AXONF_PINGROUP(F_GPIO_X4_P19, F_GPIO_X4_P19),
	AXONF_PINGROUP(F_GPIO_X4_P20, F_GPIO_X4_P20),
	AXONF_PINGROUP(F_GPIO_X4_P32, F_GPIO_X4_P32),
	AXONF_PINGROUP(F_GPIO_X4_P34, F_GPIO_X4_P34),
	AXONF_PINGROUP(F_GPIO_X4_P40, F_GPIO_X4_P40),
	AXONF_PINGROUP(F_DISP_DAT00, F_DISP_DAT00),
	AXONF_PINGROUP(F_DISP_DAT01, F_DISP_DAT01),
	AXONF_PINGROUP(F_DISP_DAT02, F_DISP_DAT02),
	AXONF_PINGROUP(F_DISP_DAT03, F_DISP_DAT03),
	AXONF_PINGROUP(F_DISP_DAT04, F_DISP_DAT04),
	AXONF_PINGROUP(F_DISP_DAT05, F_DISP_DAT05),
	AXONF_PINGROUP(F_DISP_DAT06, F_DISP_DAT06),
	AXONF_PINGROUP(F_DISP_DAT07, F_DISP_DAT07),
	AXONF_PINGROUP(F_DISP_DAT08, F_DISP_DAT08),
	AXONF_PINGROUP(F_DISP_DAT09, F_DISP_DAT09),
	AXONF_PINGROUP(F_DISP_DAT10, F_DISP_DAT10),
	AXONF_PINGROUP(F_DISP_DAT11, F_DISP_DAT11),
	AXONF_PINGROUP(F_DISP_DAT12, F_DISP_DAT12),
	AXONF_PINGROUP(F_DISP_DAT13, F_DISP_DAT13),
	AXONF_PINGROUP(F_DISP_DAT14, F_DISP_DAT14),
	AXONF_PINGROUP(F_DISP_DAT15, F_DISP_DAT15),
	AXONF_PINGROUP(F_DISP_DAT16, F_DISP_DAT16),
	AXONF_PINGROUP(F_DISP_DAT17, F_DISP_DAT17),
	AXONF_PINGROUP(F_DISP_DAT18, F_DISP_DAT18),
	AXONF_PINGROUP(F_DISP_DAT19, F_DISP_DAT19),
	AXONF_PINGROUP(F_DISP_DAT20, F_DISP_DAT20),
	AXONF_PINGROUP(F_DISP_DAT21, F_DISP_DAT21),
	AXONF_PINGROUP(F_DISP_DAT22, F_DISP_DAT22),
	AXONF_PINGROUP(F_DISP_DAT23, F_DISP_DAT23),
	AXONF_PINGROUP(F_DISP_HSYNC, F_DISP_HSYNC),
	AXONF_PINGROUP(F_DISP_VSYNC, F_DISP_VSYNC),
	AXONF_PINGROUP(F_DISP_CLK, F_DISP_CLK),
	AXONF_PINGROUP(F_DISP_BKLEN, F_DISP_BKLEN),
	AXONF_PINGROUP(F_DISP_DRDY, F_DISP_DRDY),
	AXONF_PINGROUP(F_UART_A_TXD, F_UART_A_TXD),
	AXONF_PINGROUP(F_UART_A_RXD, F_UART_A_RXD),
	AXONF_PINGROUP(F_UART_A_RTS, F_UART_A_RTS),
	AXONF_PINGROUP(F_UART_A_CTS, F_UART_A_CTS),
	AXONF_PINGROUP(F_UART_B_TXD, F_UART_B_TXD),
	AXONF_PINGROUP(F_UART_B_RXD, F_UART_B_RXD),
	AXONF_PINGROUP(F_UART_B_RTS, F_UART_B_RTS),
	AXONF_PINGROUP(F_UART_B_CTS, F_UART_B_CTS),
	AXONF_PINGROUP(F_UART_C_TXD, F_UART_C_TXD),
	AXONF_PINGROUP(F_UART_C_RXD, F_UART_C_RXD),
	AXONF_PINGROUP(F_UART_C_RTS, F_UART_C_RTS),
	AXONF_PINGROUP(F_UART_C_CTS, F_UART_C_CTS),
	AXONF_PINGROUP(F_AUD_A_TXD, F_AUD_A_TXD),
	AXONF_PINGROUP(F_AUD_A_TXFS, F_AUD_A_TXFS),
	AXONF_PINGROUP(F_AUD_A_TXCLK, F_AUD_A_TXCLK),
	AXONF_PINGROUP(F_AUD_A_RXD, F_AUD_A_RXD),
	AXONF_PINGROUP(F_SPI_A_MISO, F_SPI_A_MISO),
	AXONF_PINGROUP(F_SPI_A_MOSI, F_SPI_A_MOSI),
	AXONF_PINGROUP(F_SPI_A_SCLK, F_SPI_A_SCLK),
	AXONF_PINGROUP(F_SPI_A_CS0, F_SPI_A_CS0),
	AXONF_PINGROUP(F_SPI_A_CS1, F_SPI_A_CS1),
	AXONF_PINGROUP(F_PWM_X1_P39, F_PWM_X1_P39),
	AXONF_PINGROUP(F_PWM_X2_P79, F_PWM_X2_P79),
	AXONF_PINGROUP(F_SPI_B_MISO, F_SPI_B_MISO),
	AXONF_PINGROUP(F_SPI_B_MOSI, F_SPI_B_MOSI),
	AXONF_PINGROUP(F_SPI_B_SCLK, F_SPI_B_SCLK),
	AXONF_PINGROUP(F_SPI_B_CS0, F_SPI_B_CS0),
	AXONF_PINGROUP(F_SPI_B_CS1, F_SPI_B_CS1),
	AXONF_PINGROUP(F_PWM_X4_P1, F_PWM_X4_P1),
	AXONF_PINGROUP(F_PWM_X4_P2, F_PWM_X4_P2),
	AXONF_PINGROUP(F_UART_BT_TXD, F_UART_BT_TXD),
	AXONF_PINGROUP(F_UART_BT_RXD, F_UART_BT_RXD),
	AXONF_PINGROUP(F_UART_BT_RTS, F_UART_BT_RTS),
	AXONF_PINGROUP(F_UART_BT_CTS, F_UART_BT_CTS),
	AXONF_PINGROUP(F_CAN_A_TX, F_CAN_A_TX),
	AXONF_PINGROUP(F_CAN_A_RX, F_CAN_A_RX),
	AXONF_PINGROUP(F_CAN_B_TX, F_CAN_B_TX),
	AXONF_PINGROUP(F_CAN_B_RX, F_CAN_B_RX),
	AXONF_PINGROUP(F_AUD_B_TXD, F_AUD_B_TXD),
	AXONF_PINGROUP(F_AUD_B_TXFS, F_AUD_B_TXFS),
	AXONF_PINGROUP(F_AUD_B_TXCLK, F_AUD_B_TXCLK),
	AXONF_PINGROUP(F_AUD_B_RXD, F_AUD_B_RXD),
	AXONF_PINGROUP(F_AUD_B_RXFS, F_AUD_B_RXFS),
	AXONF_PINGROUP(F_AUD_B_RXCLK, F_AUD_B_RXCLK),
	AXONF_PINGROUP(F_AUD_B_MCLK, F_AUD_B_MCLK),
};



#endif /*__AXONFABRIC_PINS_H*/
