/*
 *  Copyright (C) 2020 TechNexion Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


#ifndef __AXONFABRIC_PINS_H
#define __AXONFABRIC_PINS_H


#include <linux/pinctrl/pinctrl.h>


#define AXONF_PIN_DESC(name) PINCTRL_PIN(AXONF_PIN_ ## name, #name)

struct axonf_pingroup {
	const char *name;
	const unsigned pins[1];
	unsigned npins;
};

#define AXONF_PIN_GPIO_X1_P66 	0
#define AXONF_PIN_GPIO_X1_P68 	1
#define AXONF_PIN_GPIO_X1_P70 	2
#define AXONF_PIN_GPIO_X1_P72 	3
#define AXONF_PIN_GPIO_X1_P74 	4
#define AXONF_PIN_GPIO_X1_P76 	5
#define AXONF_PIN_GPIO_X1_P78 	6
#define AXONF_PIN_GPIO_X1_P80 	7
#define AXONF_PIN_GPIO_X2_P18 	8
#define AXONF_PIN_GPIO_X2_P20 	9
#define AXONF_PIN_GPIO_X2_P22 	10
#define AXONF_PIN_GPIO_X2_P24 	11
#define AXONF_PIN_GPIO_X3_P65 	12
#define AXONF_PIN_GPIO_X3_P67 	13
#define AXONF_PIN_GPIO_X3_P69 	14
#define AXONF_PIN_GPIO_X3_P71 	15
#define AXONF_PIN_GPIO_X4_P7 	16
#define AXONF_PIN_GPIO_X4_P8 	17
#define AXONF_PIN_GPIO_X4_P19 	18
#define AXONF_PIN_GPIO_X4_P20 	19
#define AXONF_PIN_GPIO_X4_P32 	20
#define AXONF_PIN_GPIO_X4_P34 	21
#define AXONF_PIN_GPIO_X4_P40 	22
#define AXONF_PIN_DISP_DAT00 	24
#define AXONF_PIN_DISP_DAT01 	25
#define AXONF_PIN_DISP_DAT02 	26
#define AXONF_PIN_DISP_DAT03 	27
#define AXONF_PIN_DISP_DAT04 	28
#define AXONF_PIN_DISP_DAT05 	29
#define AXONF_PIN_DISP_DAT06 	30
#define AXONF_PIN_DISP_DAT07 	31
#define AXONF_PIN_DISP_DAT08 	32
#define AXONF_PIN_DISP_DAT09 	33
#define AXONF_PIN_DISP_DAT10 	34
#define AXONF_PIN_DISP_DAT11 	35
#define AXONF_PIN_DISP_DAT12 	36
#define AXONF_PIN_DISP_DAT13 	37
#define AXONF_PIN_DISP_DAT14 	38
#define AXONF_PIN_DISP_DAT15 	39
#define AXONF_PIN_DISP_DAT16 	40
#define AXONF_PIN_DISP_DAT17 	41
#define AXONF_PIN_DISP_DAT18 	42
#define AXONF_PIN_DISP_DAT19 	43
#define AXONF_PIN_DISP_DAT20 	44
#define AXONF_PIN_DISP_DAT21 	45
#define AXONF_PIN_DISP_DAT22 	46
#define AXONF_PIN_DISP_DAT23 	47
#define AXONF_PIN_DISP_HSYNC 	48
#define AXONF_PIN_DISP_VSYNC 	49
#define AXONF_PIN_DISP_CLK 	50
#define AXONF_PIN_DISP_BKLEN 	51
#define AXONF_PIN_DISP_DRDY 	52
#define AXONF_PIN_UART_A_TXD 	56
#define AXONF_PIN_UART_A_RXD 	57
#define AXONF_PIN_UART_A_RTS 	58
#define AXONF_PIN_UART_A_CTS 	59
#define AXONF_PIN_UART_B_TXD 	60
#define AXONF_PIN_UART_B_RXD 	61
#define AXONF_PIN_UART_B_RTS 	62
#define AXONF_PIN_UART_B_CTS 	63
#define AXONF_PIN_UART_C_TXD 	64
#define AXONF_PIN_UART_C_RXD 	65
#define AXONF_PIN_UART_C_RTS 	66
#define AXONF_PIN_UART_C_CTS 	67
#define AXONF_PIN_AUD_A_TXD 	68
#define AXONF_PIN_AUD_A_TXFS 	69
#define AXONF_PIN_AUD_A_TXCLK 	70
#define AXONF_PIN_AUD_A_RXD 	71
#define AXONF_PIN_SPI_A_MISO 	72
#define AXONF_PIN_SPI_A_MOSI 	73
#define AXONF_PIN_SPI_A_SCLK 	74
#define AXONF_PIN_SPI_A_CS0 	75
#define AXONF_PIN_SPI_A_CS1 	76
#define AXONF_PIN_PWM_X1_P39 	77
#define AXONF_PIN_PWM_X2_P79 	78
#define AXONF_PIN_SPI_B_MISO 	80
#define AXONF_PIN_SPI_B_MOSI 	81
#define AXONF_PIN_SPI_B_SCLK 	82
#define AXONF_PIN_SPI_B_CS0 	83
#define AXONF_PIN_SPI_B_CS1 	84
#define AXONF_PIN_PWM_X4_P1 	85
#define AXONF_PIN_PWM_X4_P2 	86
#define AXONF_PIN_UART_BT_TXD 	88
#define AXONF_PIN_UART_BT_RXD 	89
#define AXONF_PIN_UART_BT_RTS 	90
#define AXONF_PIN_UART_BT_CTS 	91
#define AXONF_PIN_CAN_A_TX 	92
#define AXONF_PIN_CAN_A_RX 	93
#define AXONF_PIN_CAN_B_TX 	94
#define AXONF_PIN_CAN_B_RX 	95
#define AXONF_PIN_AUD_B_TXD 	96
#define AXONF_PIN_AUD_B_TXFS 	97
#define AXONF_PIN_AUD_B_TXCLK 	98
#define AXONF_PIN_AUD_B_RXD 	99
#define AXONF_PIN_AUD_B_RXFS 	100
#define AXONF_PIN_AUD_B_RXCLK 	101
#define AXONF_PIN_AUD_B_MCLK 	102

/* PINCTRL DESC */

static const struct pinctrl_pin_desc axonf_pins_desc[] = {
	AXONF_PIN_DESC(GPIO_X1_P66),
	AXONF_PIN_DESC(GPIO_X1_P68),
	AXONF_PIN_DESC(GPIO_X1_P70),
	AXONF_PIN_DESC(GPIO_X1_P72),
	AXONF_PIN_DESC(GPIO_X1_P74),
	AXONF_PIN_DESC(GPIO_X1_P76),
	AXONF_PIN_DESC(GPIO_X1_P78),
	AXONF_PIN_DESC(GPIO_X1_P80),
	AXONF_PIN_DESC(GPIO_X2_P18),
	AXONF_PIN_DESC(GPIO_X2_P20),
	AXONF_PIN_DESC(GPIO_X2_P22),
	AXONF_PIN_DESC(GPIO_X2_P24),
	AXONF_PIN_DESC(GPIO_X3_P65),
	AXONF_PIN_DESC(GPIO_X3_P67),
	AXONF_PIN_DESC(GPIO_X3_P69),
	AXONF_PIN_DESC(GPIO_X3_P71),
	AXONF_PIN_DESC(GPIO_X4_P7),
	AXONF_PIN_DESC(GPIO_X4_P8),
	AXONF_PIN_DESC(GPIO_X4_P19),
	AXONF_PIN_DESC(GPIO_X4_P20),
	AXONF_PIN_DESC(GPIO_X4_P32),
	AXONF_PIN_DESC(GPIO_X4_P34),
	AXONF_PIN_DESC(GPIO_X4_P40),
	AXONF_PIN_DESC(DISP_DAT00),
	AXONF_PIN_DESC(DISP_DAT01),
	AXONF_PIN_DESC(DISP_DAT02),
	AXONF_PIN_DESC(DISP_DAT03),
	AXONF_PIN_DESC(DISP_DAT04),
	AXONF_PIN_DESC(DISP_DAT05),
	AXONF_PIN_DESC(DISP_DAT06),
	AXONF_PIN_DESC(DISP_DAT07),
	AXONF_PIN_DESC(DISP_DAT08),
	AXONF_PIN_DESC(DISP_DAT09),
	AXONF_PIN_DESC(DISP_DAT10),
	AXONF_PIN_DESC(DISP_DAT11),
	AXONF_PIN_DESC(DISP_DAT12),
	AXONF_PIN_DESC(DISP_DAT13),
	AXONF_PIN_DESC(DISP_DAT14),
	AXONF_PIN_DESC(DISP_DAT15),
	AXONF_PIN_DESC(DISP_DAT16),
	AXONF_PIN_DESC(DISP_DAT17),
	AXONF_PIN_DESC(DISP_DAT18),
	AXONF_PIN_DESC(DISP_DAT19),
	AXONF_PIN_DESC(DISP_DAT20),
	AXONF_PIN_DESC(DISP_DAT21),
	AXONF_PIN_DESC(DISP_DAT22),
	AXONF_PIN_DESC(DISP_DAT23),
	AXONF_PIN_DESC(DISP_HSYNC),
	AXONF_PIN_DESC(DISP_VSYNC),
	AXONF_PIN_DESC(DISP_CLK),
	AXONF_PIN_DESC(DISP_BKLEN),
	AXONF_PIN_DESC(DISP_DRDY),
	AXONF_PIN_DESC(UART_A_TXD),
	AXONF_PIN_DESC(UART_A_RXD),
	AXONF_PIN_DESC(UART_A_RTS),
	AXONF_PIN_DESC(UART_A_CTS),
	AXONF_PIN_DESC(UART_B_TXD),
	AXONF_PIN_DESC(UART_B_RXD),
	AXONF_PIN_DESC(UART_B_RTS),
	AXONF_PIN_DESC(UART_B_CTS),
	AXONF_PIN_DESC(UART_C_TXD),
	AXONF_PIN_DESC(UART_C_RXD),
	AXONF_PIN_DESC(UART_C_RTS),
	AXONF_PIN_DESC(UART_C_CTS),
	AXONF_PIN_DESC(AUD_A_TXD),
	AXONF_PIN_DESC(AUD_A_TXFS),
	AXONF_PIN_DESC(AUD_A_TXCLK),
	AXONF_PIN_DESC(AUD_A_RXD),
	AXONF_PIN_DESC(SPI_A_MISO),
	AXONF_PIN_DESC(SPI_A_MOSI),
	AXONF_PIN_DESC(SPI_A_SCLK),
	AXONF_PIN_DESC(SPI_A_CS0),
	AXONF_PIN_DESC(SPI_A_CS1),
	AXONF_PIN_DESC(PWM_X1_P39),
	AXONF_PIN_DESC(PWM_X2_P79),
	AXONF_PIN_DESC(SPI_B_MISO),
	AXONF_PIN_DESC(SPI_B_MOSI),
	AXONF_PIN_DESC(SPI_B_SCLK),
	AXONF_PIN_DESC(SPI_B_CS0),
	AXONF_PIN_DESC(SPI_B_CS1),
	AXONF_PIN_DESC(PWM_X4_P1),
	AXONF_PIN_DESC(PWM_X4_P2),
	AXONF_PIN_DESC(UART_BT_TXD),
	AXONF_PIN_DESC(UART_BT_RXD),
	AXONF_PIN_DESC(UART_BT_RTS),
	AXONF_PIN_DESC(UART_BT_CTS),
	AXONF_PIN_DESC(CAN_A_TX),
	AXONF_PIN_DESC(CAN_A_RX),
	AXONF_PIN_DESC(CAN_B_TX),
	AXONF_PIN_DESC(CAN_B_RX),
	AXONF_PIN_DESC(AUD_B_TXD),
	AXONF_PIN_DESC(AUD_B_TXFS),
	AXONF_PIN_DESC(AUD_B_TXCLK),
	AXONF_PIN_DESC(AUD_B_RXD),
	AXONF_PIN_DESC(AUD_B_RXFS),
	AXONF_PIN_DESC(AUD_B_RXCLK),
	AXONF_PIN_DESC(AUD_B_MCLK),
};


/* GPIO groups */

static const char * const gpio_groups[] = {
	"GPIO_X1_P66",
	"GPIO_X1_P68",
	"GPIO_X1_P70",
	"GPIO_X1_P72",
	"GPIO_X1_P74",
	"GPIO_X1_P76",
	"GPIO_X1_P78",
	"GPIO_X1_P80",
	"GPIO_X2_P18",
	"GPIO_X2_P20",
	"GPIO_X2_P22",
	"GPIO_X2_P24",
	"GPIO_X3_P65",
	"GPIO_X3_P67",
	"GPIO_X3_P69",
	"GPIO_X3_P71",
	"GPIO_X4_P7",
	"GPIO_X4_P8",
	"GPIO_X4_P19",
	"GPIO_X4_P20",
	"GPIO_X4_P32",
	"GPIO_X4_P34",
	"GPIO_X4_P40",
	"DISP_DAT00",
	"DISP_DAT01",
	"DISP_DAT02",
	"DISP_DAT03",
	"DISP_DAT04",
	"DISP_DAT05",
	"DISP_DAT06",
	"DISP_DAT07",
	"DISP_DAT08",
	"DISP_DAT09",
	"DISP_DAT10",
	"DISP_DAT11",
	"DISP_DAT12",
	"DISP_DAT13",
	"DISP_DAT14",
	"DISP_DAT15",
	"DISP_DAT16",
	"DISP_DAT17",
	"DISP_DAT18",
	"DISP_DAT19",
	"DISP_DAT20",
	"DISP_DAT21",
	"DISP_DAT22",
	"DISP_DAT23",
	"DISP_HSYNC",
	"DISP_VSYNC",
	"DISP_CLK",
	"DISP_BKLEN",
	"DISP_DRDY",
	"UART_A_TXD",
	"UART_A_RXD",
	"UART_A_RTS",
	"UART_A_CTS",
	"UART_B_TXD",
	"UART_B_RXD",
	"UART_B_RTS",
	"UART_B_CTS",
	"UART_C_TXD",
	"UART_C_RXD",
	"UART_C_RTS",
	"UART_C_CTS",
	"AUD_A_TXD",
	"AUD_A_TXFS",
	"AUD_A_TXCLK",
	"AUD_A_RXD",
	"SPI_A_MISO",
	"SPI_A_MOSI",
	"SPI_A_SCLK",
	"SPI_A_CS0",
	"SPI_A_CS1",
	"PWM_X1_P39",
	"PWM_X2_P79",
	"SPI_B_MISO",
	"SPI_B_MOSI",
	"SPI_B_SCLK",
	"SPI_B_CS0",
	"SPI_B_CS1",
	"PWM_X4_P1",
	"PWM_X4_P2",
	"UART_BT_TXD",
	"UART_BT_RXD",
	"UART_BT_RTS",
	"UART_BT_CTS",
	"CAN_A_TX",
	"CAN_A_RX",
	"CAN_B_TX",
	"CAN_B_RX",
	"AUD_B_TXD",
	"AUD_B_TXFS",
	"AUD_B_TXCLK",
	"AUD_B_RXD",
	"AUD_B_RXFS",
	"AUD_B_RXCLK",
	"AUD_B_MCLK",
};


/* Pin groups */

#define AXONF_PINGROUP(pg_name, pin_id) {.name = #pg_name,	.pins = {AXONF_PIN_##pin_id}, .npins = 1,}

static const struct axonf_pingroup axonf_pingroups[] = {
	AXONF_PINGROUP(GPIO_X1_P66, GPIO_X1_P66),
	AXONF_PINGROUP(GPIO_X1_P68, GPIO_X1_P68),
	AXONF_PINGROUP(GPIO_X1_P70, GPIO_X1_P70),
	AXONF_PINGROUP(GPIO_X1_P72, GPIO_X1_P72),
	AXONF_PINGROUP(GPIO_X1_P74, GPIO_X1_P74),
	AXONF_PINGROUP(GPIO_X1_P76, GPIO_X1_P76),
	AXONF_PINGROUP(GPIO_X1_P78, GPIO_X1_P78),
	AXONF_PINGROUP(GPIO_X1_P80, GPIO_X1_P80),
	AXONF_PINGROUP(GPIO_X2_P18, GPIO_X2_P18),
	AXONF_PINGROUP(GPIO_X2_P20, GPIO_X2_P20),
	AXONF_PINGROUP(GPIO_X2_P22, GPIO_X2_P22),
	AXONF_PINGROUP(GPIO_X2_P24, GPIO_X2_P24),
	AXONF_PINGROUP(GPIO_X3_P65, GPIO_X3_P65),
	AXONF_PINGROUP(GPIO_X3_P67, GPIO_X3_P67),
	AXONF_PINGROUP(GPIO_X3_P69, GPIO_X3_P69),
	AXONF_PINGROUP(GPIO_X3_P71, GPIO_X3_P71),
	AXONF_PINGROUP(GPIO_X4_P7, GPIO_X4_P7),
	AXONF_PINGROUP(GPIO_X4_P8, GPIO_X4_P8),
	AXONF_PINGROUP(GPIO_X4_P19, GPIO_X4_P19),
	AXONF_PINGROUP(GPIO_X4_P20, GPIO_X4_P20),
	AXONF_PINGROUP(GPIO_X4_P32, GPIO_X4_P32),
	AXONF_PINGROUP(GPIO_X4_P34, GPIO_X4_P34),
	AXONF_PINGROUP(GPIO_X4_P40, GPIO_X4_P40),
	AXONF_PINGROUP(DISP_DAT00, DISP_DAT00),
	AXONF_PINGROUP(DISP_DAT01, DISP_DAT01),
	AXONF_PINGROUP(DISP_DAT02, DISP_DAT02),
	AXONF_PINGROUP(DISP_DAT03, DISP_DAT03),
	AXONF_PINGROUP(DISP_DAT04, DISP_DAT04),
	AXONF_PINGROUP(DISP_DAT05, DISP_DAT05),
	AXONF_PINGROUP(DISP_DAT06, DISP_DAT06),
	AXONF_PINGROUP(DISP_DAT07, DISP_DAT07),
	AXONF_PINGROUP(DISP_DAT08, DISP_DAT08),
	AXONF_PINGROUP(DISP_DAT09, DISP_DAT09),
	AXONF_PINGROUP(DISP_DAT10, DISP_DAT10),
	AXONF_PINGROUP(DISP_DAT11, DISP_DAT11),
	AXONF_PINGROUP(DISP_DAT12, DISP_DAT12),
	AXONF_PINGROUP(DISP_DAT13, DISP_DAT13),
	AXONF_PINGROUP(DISP_DAT14, DISP_DAT14),
	AXONF_PINGROUP(DISP_DAT15, DISP_DAT15),
	AXONF_PINGROUP(DISP_DAT16, DISP_DAT16),
	AXONF_PINGROUP(DISP_DAT17, DISP_DAT17),
	AXONF_PINGROUP(DISP_DAT18, DISP_DAT18),
	AXONF_PINGROUP(DISP_DAT19, DISP_DAT19),
	AXONF_PINGROUP(DISP_DAT20, DISP_DAT20),
	AXONF_PINGROUP(DISP_DAT21, DISP_DAT21),
	AXONF_PINGROUP(DISP_DAT22, DISP_DAT22),
	AXONF_PINGROUP(DISP_DAT23, DISP_DAT23),
	AXONF_PINGROUP(DISP_HSYNC, DISP_HSYNC),
	AXONF_PINGROUP(DISP_VSYNC, DISP_VSYNC),
	AXONF_PINGROUP(DISP_CLK, DISP_CLK),
	AXONF_PINGROUP(DISP_BKLEN, DISP_BKLEN),
	AXONF_PINGROUP(DISP_DRDY, DISP_DRDY),
	AXONF_PINGROUP(UART_A_TXD, UART_A_TXD),
	AXONF_PINGROUP(UART_A_RXD, UART_A_RXD),
	AXONF_PINGROUP(UART_A_RTS, UART_A_RTS),
	AXONF_PINGROUP(UART_A_CTS, UART_A_CTS),
	AXONF_PINGROUP(UART_B_TXD, UART_B_TXD),
	AXONF_PINGROUP(UART_B_RXD, UART_B_RXD),
	AXONF_PINGROUP(UART_B_RTS, UART_B_RTS),
	AXONF_PINGROUP(UART_B_CTS, UART_B_CTS),
	AXONF_PINGROUP(UART_C_TXD, UART_C_TXD),
	AXONF_PINGROUP(UART_C_RXD, UART_C_RXD),
	AXONF_PINGROUP(UART_C_RTS, UART_C_RTS),
	AXONF_PINGROUP(UART_C_CTS, UART_C_CTS),
	AXONF_PINGROUP(AUD_A_TXD, AUD_A_TXD),
	AXONF_PINGROUP(AUD_A_TXFS, AUD_A_TXFS),
	AXONF_PINGROUP(AUD_A_TXCLK, AUD_A_TXCLK),
	AXONF_PINGROUP(AUD_A_RXD, AUD_A_RXD),
	AXONF_PINGROUP(SPI_A_MISO, SPI_A_MISO),
	AXONF_PINGROUP(SPI_A_MOSI, SPI_A_MOSI),
	AXONF_PINGROUP(SPI_A_SCLK, SPI_A_SCLK),
	AXONF_PINGROUP(SPI_A_CS0, SPI_A_CS0),
	AXONF_PINGROUP(SPI_A_CS1, SPI_A_CS1),
	AXONF_PINGROUP(PWM_X1_P39, PWM_X1_P39),
	AXONF_PINGROUP(PWM_X2_P79, PWM_X2_P79),
	AXONF_PINGROUP(SPI_B_MISO, SPI_B_MISO),
	AXONF_PINGROUP(SPI_B_MOSI, SPI_B_MOSI),
	AXONF_PINGROUP(SPI_B_SCLK, SPI_B_SCLK),
	AXONF_PINGROUP(SPI_B_CS0, SPI_B_CS0),
	AXONF_PINGROUP(SPI_B_CS1, SPI_B_CS1),
	AXONF_PINGROUP(PWM_X4_P1, PWM_X4_P1),
	AXONF_PINGROUP(PWM_X4_P2, PWM_X4_P2),
	AXONF_PINGROUP(UART_BT_TXD, UART_BT_TXD),
	AXONF_PINGROUP(UART_BT_RXD, UART_BT_RXD),
	AXONF_PINGROUP(UART_BT_RTS, UART_BT_RTS),
	AXONF_PINGROUP(UART_BT_CTS, UART_BT_CTS),
	AXONF_PINGROUP(CAN_A_TX, CAN_A_TX),
	AXONF_PINGROUP(CAN_A_RX, CAN_A_RX),
	AXONF_PINGROUP(CAN_B_TX, CAN_B_TX),
	AXONF_PINGROUP(CAN_B_RX, CAN_B_RX),
	AXONF_PINGROUP(AUD_B_TXD, AUD_B_TXD),
	AXONF_PINGROUP(AUD_B_TXFS, AUD_B_TXFS),
	AXONF_PINGROUP(AUD_B_TXCLK, AUD_B_TXCLK),
	AXONF_PINGROUP(AUD_B_RXD, AUD_B_RXD),
	AXONF_PINGROUP(AUD_B_RXFS, AUD_B_RXFS),
	AXONF_PINGROUP(AUD_B_RXCLK, AUD_B_RXCLK),
	AXONF_PINGROUP(AUD_B_MCLK, AUD_B_MCLK),
};



#endif /*__AXONFABRIC_PINS_H*/
